backend:
  name: git-gateway
  branch: main

media_folder: "imagenes/uploads"
public_folder: "/imagenes/uploads"

collections:
  - name: "pagina"
    label: "Contenido Web"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Titulo", name: "titulo", widget: "string" }
          - { label: "Descripcion", name: "descripcion", widget: "text" }
          - { label: "Imagen principal", name: "imagen", widget: "image" }